In [1]:
import numpy as np

In [2]:
my_list = [10, 20, 30, 40]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)


array([10, 20, 30, 40])

In [5]:
my_numpy_array = np.array(my_list)

In [6]:
type(my_numpy_array)

numpy.ndarray

In [7]:
my_numpy_array.max()

np.int64(40)

In [8]:
numpy.ones(6)

NameError: name 'numpy' is not defined

In [9]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
np.random.random(5)

array([0.52831554, 0.67467964, 0.4334797 , 0.29364159, 0.6859611 ])

In [12]:
# array arithmetic

In [13]:
 np_array = np.arange(0, 20, 4)

In [14]:
np_array[4]

np.int64(16)

In [15]:
np_array[-1::-1]

array([16, 12,  8,  4,  0])

In [16]:
np.random.randn(4,3)

array([[-0.03238321,  1.17600071,  0.30972367],
       [ 2.23821706,  1.02006698,  0.47812065],
       [-0.35176062, -1.38447515, -1.08722754],
       [ 1.33881639,  0.27951794,  2.18874424]])