In [1]:
import numpy as np

In [2]:
matrix = [[5,10],[15,20]]

In [3]:
type(matrix)

list

In [4]:
matrix[1][0]

15

In [5]:
matrix[1][-1]

20

In [6]:
nMatrix = np.array([[10, 20],[30, 40]])

In [7]:
nMatrix

array([[10, 20],
       [30, 40]])

In [8]:
nMatrix[0][0]

np.int64(10)

In [9]:
nMatrix.sum()

np.int64(100)

In [10]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [11]:
mMatrix = np.array([[100, 2],[300, 4]])

In [12]:
nMatrix

array([[10, 20],
       [30, 40]])

In [13]:
mMatrix

array([[100,   2],
       [300,   4]])

In [14]:
nMatrix + mMatrix

array([[110,  22],
       [330,  44]])

In [15]:
row_matrix = np.array([[70, 75]])

In [16]:
row_matrix

array([[70, 75]])

In [17]:
mMatrix + row_matrix

array([[170,  77],
       [370,  79]])

In [18]:
nMatrix

array([[10, 20],
       [30, 40]])

In [19]:
mMatrix

array([[100,   2],
       [300,   4]])

In [20]:
nMatrix * mMatrix

array([[1000,   40],
       [9000,  160]])

In [23]:
#np.mul

In [22]:
np.multiply(nMatrix, mMatrix)

array([[1000,   40],
       [9000,  160]])

In [24]:
np.dot(nMatrix, mMatrix)

array([[ 7000,   100],
       [15000,   220]])

In [25]:
nMatrix(nMatrix > 10)

TypeError: 'numpy.ndarray' object is not callable

In [26]:
xMatrix = np.random.randint(1, 1000, 50)

In [27]:
xMatrix

array([880, 610, 747, 734, 117, 480, 489, 978, 604, 969, 667, 473,  24,
       933, 688,  39, 364,  74, 139, 132, 805, 118, 471, 589, 705, 625,
       227, 616,  40, 604, 917, 448, 311, 621, 854, 525, 612, 254, 343,
       566, 565, 458, 462, 365, 368, 703, 473, 963, 988, 631], dtype=int32)

In [28]:
xMatrix[xMatrix > 200]

array([880, 610, 747, 734, 480, 489, 978, 604, 969, 667, 473, 933, 688,
       364, 805, 471, 589, 705, 625, 227, 616, 604, 917, 448, 311, 621,
       854, 525, 612, 254, 343, 566, 565, 458, 462, 365, 368, 703, 473,
       963, 988, 631], dtype=int32)

In [30]:
xMatrix.transpose()

array([880, 610, 747, 734, 117, 480, 489, 978, 604, 969, 667, 473,  24,
       933, 688,  39, 364,  74, 139, 132, 805, 118, 471, 589, 705, 625,
       227, 616,  40, 604, 917, 448, 311, 621, 854, 525, 612, 254, 343,
       566, 565, 458, 462, 365, 368, 703, 473, 963, 988, 631], dtype=int32)

In [31]:
yMatrix = np.array([np.random.randint(1,100, 5), np.random.randint(1,100, 5), np.random.randint(1,100, 5), np.random.randint(1,100, 5), np.random.randint(1,100, 5)])

In [32]:
yMatrix

array([[62, 97, 39, 36, 54],
       [14, 12, 89,  9,  8],
       [29, 20, 51, 64, 23],
       [76, 87, 85,  1,  1],
       [29,  9, 30, 23, 55]], dtype=int32)

In [33]:
yMatrix.T

array([[62, 14, 29, 76, 29],
       [97, 12, 20, 87,  9],
       [39, 89, 51, 85, 30],
       [36,  9, 64,  1, 23],
       [54,  8, 23,  1, 55]], dtype=int32)

In [34]:
xMatrix.reshape(20, -1)

ValueError: cannot reshape array of size 50 into shape (20,newaxis)

In [36]:
xMatrix.reshape(10, -1)

array([[880, 610, 747, 734, 117],
       [480, 489, 978, 604, 969],
       [667, 473,  24, 933, 688],
       [ 39, 364,  74, 139, 132],
       [805, 118, 471, 589, 705],
       [625, 227, 616,  40, 604],
       [917, 448, 311, 621, 854],
       [525, 612, 254, 343, 566],
       [565, 458, 462, 365, 368],
       [703, 473, 963, 988, 631]], dtype=int32)

In [37]:
data = np.array([10, 12, 13, 14, 18, 25, 100, 105])

In [38]:
mean = np.mean(data)

In [39]:
mean

np.float64(37.125)

In [40]:
std = np.std(data)

In [41]:
std

np.float64(38.00801724636527)

In [42]:
z_scores = (data - mean) / std

In [44]:
z_scores

array([-0.71366522, -0.66104474, -0.6347345 , -0.60842427, -0.50318331,
       -0.31901164,  1.65425625,  1.78580744])

In [45]:
z_scores[z_scores > 1]

array([1.65425625, 1.78580744])

In [46]:
data[z_scores > 1]

array([100, 105])

In [47]:
# 2x + 3y = 8, 5x + 7y = 19

In [49]:
coefficients = np.array([[2,3],[5,7]])

In [50]:
constants = np.array([8,19])

In [51]:
solution = np.linalg.solve(coefficients, constants)

In [52]:
solution

array([1., 2.])