In [4]:
import torch

In [14]:
tensor = torch.arange(0, 50, 5)
print(f"tensor: {tensor}")
print(f"\ntensor.min(): {tensor.min()}")
print(f"tensor.max(): {tensor.max()}")
print(f"\ntensor.median(): {tensor.median()}")
print(f"\ntensor.sum(): {tensor.sum()}")

tensor: tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

tensor.min(): 0
tensor.max(): 45

tensor.median(): 20

tensor.sum(): 225


In [11]:
tensor = tensor.type(torch.float)
print(f"tensor.mean(): {tensor.mean()}")

tensor.mean(): 22.5


### argmax, argmin

In [15]:
print(f"tensor.argmin(): {tensor.argmin()}")
print(f"tensor.argmax(): {tensor.argmax()}")

tensor.argmin(): 0
tensor.argmax(): 9


### Manipulating Tensor: reshaping, stacking, squeezing, unsqueezing

In [17]:
x = torch.arange(1, 10, 1)
print(f"x: {x}")
print(f"x.shape: {x.shape}")
print(f"x.ndim: {x.ndim}")

x: tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
x.shape: torch.Size([9])
x.ndim: 1


In [25]:
y = torch.randn(size = (224, 224, 3))
print(f"y.shape: {y.shape}")
print(f"y.ndim: {y.ndim}")
print(f"\ny: {y}")

y.shape: torch.Size([224, 224, 3])
y.ndim: 3

y: tensor([[[ 2.5441,  1.2252, -0.3193],
         [ 1.4087,  0.0636,  1.3352],
         [-0.7458,  0.5735,  0.5128],
         ...,
         [-1.2290,  0.9325, -0.0881],
         [-1.3566, -0.1708, -1.5351],
         [ 0.7174,  2.7402,  0.1952]],

        [[ 0.9381,  1.1197, -0.4454],
         [-0.1929, -1.0626,  0.2264],
         [ 0.3376, -1.2007, -0.7735],
         ...,
         [ 0.7504, -0.3978, -0.1281],
         [ 0.2216, -0.8155, -0.5444],
         [ 1.8445, -0.4318, -0.7700]],

        [[-0.3303,  1.3953,  0.2364],
         [-0.8294, -1.9480,  1.5324],
         [ 0.4236, -0.4982,  0.7089],
         ...,
         [ 0.8228,  0.7025,  0.0133],
         [ 0.1265, -0.0187,  0.3217],
         [-1.0487, -1.4984,  1.4695]],

        ...,

        [[-0.3746,  0.5932,  0.0539],
         [-0.4473, -0.0183, -0.6007],
         [-1.2688, -0.0534, -0.3705],
         ...,
         [ 0.8485,  0.4945,  0.7405],
         [-0.2157, -0.7408, -0.1003],
 

In [36]:
x_reshaped = x.reshape(3, -1)
x_reshaped[0] = 20
x

tensor([20, 20, 20,  4,  5,  6,  7,  8,  9])

In [41]:
x_view = x.view(9, 1)
x_view[0] = 0
x_view
x

tensor([ 0, 20, 20,  4,  5,  6,  7,  8,  9])

#### view -> contigious tensor: bellekte arka arkaya saklanan tensor

In [43]:
x.is_contiguous()

True

In [72]:
contigious_tensor = torch.arange(0, 20, 1)
contigious_tensor = contigious_tensor.reshape(4, -1)
transpose_ct = contigious_tensor.T

print(f"\ncontigious_tensor:\n{contigious_tensor}")
print(f"transpose_ct:\n{transpose_ct}")

print(f"\ncontigious_tensor.is_contiguous: {contigious_tensor.is_contiguous()}")
print(f"transpose_ct.is_contiguous: {transpose_ct.is_contiguous()}")

print(f"\n\ncontigious_tensor.view(5, -1): \n{contigious_tensor.view(5, -1)}")

try:
    print(f"transpose_ct.view(5, -1): \n{transpose_ct.view(4, -1)}")
except RuntimeError:
    print("transpose_ct.view will cause an error")


contigious_tensor:
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
transpose_ct:
tensor([[ 0,  5, 10, 15],
        [ 1,  6, 11, 16],
        [ 2,  7, 12, 17],
        [ 3,  8, 13, 18],
        [ 4,  9, 14, 19]])

contigious_tensor.is_contiguous: True
transpose_ct.is_contiguous: False


contigious_tensor.view(5, -1): 
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])
transpose_ct.view will cause an error


### Stack

In [76]:
x = torch.arange(1, 7, 1)
x = x.reshape(2, -1)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [77]:
torch.stack([x, x, x, x], dim=0)

tensor([[[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]],

        [[1, 2, 3],
         [4, 5, 6]]])

### Squeeze & unsqueeze

In [79]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [85]:
print(f"x:\n{x}")
print(f"x.shape: {x.shape}")
print(f"x.ndim: {x.ndim}")

x:
tensor([[1, 2, 3],
        [4, 5, 6]])
x.shape: torch.Size([2, 3])
x.ndim: 2


In [87]:
squeezed_x = x.squeeze()
print(f"squeezed_x:\n{squeezed_x}")
print(f"squeezed_x.shape: {squeezed_x.shape}")
print(f"squeezed_x.ndim: {squeezed_x.ndim}")

squeezed_x:
tensor([[1, 2, 3],
        [4, 5, 6]])
squeezed_x.shape: torch.Size([2, 3])
squeezed_x.ndim: 2


In [89]:
x = torch.tensor([[1, 2, 3]])
print(f"x:\n{x}")
print(f"x.shape: {x.shape}")
print(f"x.ndim: {x.ndim}\n\n")

squeezed_x = x.squeeze()
print(f"squeezed_x:\n{squeezed_x}")
print(f"squeezed_x.shape: {squeezed_x.shape}")
print(f"squeezed_x.ndim: {squeezed_x.ndim}")

x:
tensor([[1, 2, 3]])
x.shape: torch.Size([1, 3])
x.ndim: 2


squeezed_x:
tensor([1, 2, 3])
squeezed_x.shape: torch.Size([3])
squeezed_x.ndim: 1


In [91]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"x:\n{x}")
print(f"x.shape: {x.shape}")
print(f"x.ndim: {x.ndim}\n\n")

squeezed_x = x.unsqueeze(dim = 0)
print(f"squeezed_x:\n{squeezed_x}")
print(f"squeezed_x.shape: {squeezed_x.shape}")
print(f"squeezed_x.ndim: {squeezed_x.ndim}")

x:
tensor([[1, 2, 3],
        [4, 5, 6]])
x.shape: torch.Size([2, 3])
x.ndim: 2


squeezed_x:
tensor([[[1, 2, 3],
         [4, 5, 6]]])
squeezed_x.shape: torch.Size([1, 2, 3])
squeezed_x.ndim: 3


### Permute

In [93]:
x = torch.rand(size=(224, 224, 3))

In [96]:
print(f"x.shape: {x.shape}")
print(f"x.ndim: {x.ndim}\n\n")
print(f"x:\n{x}")

x.shape: torch.Size([224, 224, 3])
x.ndim: 3


x:
tensor([[[0.0672, 0.0724, 0.6866],
         [0.6983, 0.0825, 0.6048],
         [0.2197, 0.9379, 0.2695],
         ...,
         [0.3926, 0.6462, 0.2933],
         [0.8465, 0.4693, 0.8458],
         [0.9770, 0.9575, 0.3675]],

        [[0.5081, 0.5203, 0.0486],
         [0.5388, 0.5239, 0.1387],
         [0.1004, 0.2127, 0.7275],
         ...,
         [0.7883, 0.4577, 0.7320],
         [0.5232, 0.9283, 0.9337],
         [0.5457, 0.0443, 0.8755]],

        [[0.5265, 0.8459, 0.2849],
         [0.0666, 0.3449, 0.4269],
         [0.3718, 0.8065, 0.8901],
         ...,
         [0.6842, 0.6638, 0.7539],
         [0.8682, 0.4843, 0.5728],
         [0.3938, 0.7518, 0.1101]],

        ...,

        [[0.7976, 0.4148, 0.5774],
         [0.8183, 0.7531, 0.4750],
         [0.9332, 0.9696, 0.3710],
         ...,
         [0.2153, 0.5473, 0.4697],
         [0.4700, 0.3465, 0.7895],
         [0.8851, 0.0475, 0.7912]],

        [[0.5135, 0.9663, 0.6675

In [97]:
x_permuted = x.permute(2, 0, 1) # axis 0 -> 1, 1 -> 2, 2->0
print(f"x_permuted.shape: {x_permuted.shape}")
print(f"x_permuted.ndim: {x_permuted.ndim}\n\n")
print(f"x_permuted:\n{x_permuted}")

x_permuted.shape: torch.Size([3, 224, 224])
x_permuted.ndim: 3


x_permuted:
tensor([[[0.0672, 0.6983, 0.2197,  ..., 0.3926, 0.8465, 0.9770],
         [0.5081, 0.5388, 0.1004,  ..., 0.7883, 0.5232, 0.5457],
         [0.5265, 0.0666, 0.3718,  ..., 0.6842, 0.8682, 0.3938],
         ...,
         [0.7976, 0.8183, 0.9332,  ..., 0.2153, 0.4700, 0.8851],
         [0.5135, 0.2971, 0.9679,  ..., 0.3646, 0.4695, 0.6764],
         [0.2179, 0.2943, 0.0822,  ..., 0.7148, 0.8983, 0.3342]],

        [[0.0724, 0.0825, 0.9379,  ..., 0.6462, 0.4693, 0.9575],
         [0.5203, 0.5239, 0.2127,  ..., 0.4577, 0.9283, 0.0443],
         [0.8459, 0.3449, 0.8065,  ..., 0.6638, 0.4843, 0.7518],
         ...,
         [0.4148, 0.7531, 0.9696,  ..., 0.5473, 0.3465, 0.0475],
         [0.9663, 0.4399, 0.4397,  ..., 0.0145, 0.1848, 0.6892],
         [0.6132, 0.4372, 0.1726,  ..., 0.8452, 0.4256, 0.6730]],

        [[0.6866, 0.6048, 0.2695,  ..., 0.2933, 0.8458, 0.3675],
         [0.0486, 0.1387, 0.7275,  ..., 0.7320

### Indexing & Slicing

In [105]:
a = torch.arange(1, 10, 1)
a

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
a = a.reshape(1, 3, 3)
a

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [103]:
a[0][0][0]

tensor(1)

In [110]:
a.shape

torch.Size([1, 3, 3])

In [111]:
a.ndim

3

In [112]:
a[:,0,0]

tensor([1])

In [113]:
a[:,1,0]

tensor([4])

In [114]:
a[:,:,0]

tensor([[1, 4, 7]])

In [115]:
a[:,0,:]

tensor([[1, 2, 3]])

### random seed

In [122]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])