In [2]:
!pip install torch torchvision

In [3]:
import torch
import numpy as np

### Pytorch Data Types - tensors

In [5]:
 torch.tensor(10)

tensor(10)

In [6]:
torch.tensor([5, 2])

tensor([5, 2])

In [7]:
scalar = torch.tensor(11)

In [8]:
type(scalar)

torch.Tensor

In [13]:
scalar.dim()

0

In [14]:
scalar.shape

torch.Size([])

In [15]:
scalar.item()

11

In [16]:
numpy_int = np.int32(10)

In [17]:
numpy_int

np.int32(10)

In [18]:
scalar - numpy_int

tensor(1)

In [19]:
scalar_from_np = torch.tensor(numpy_int)

In [20]:
scalar_from_np.dtype

torch.int32

In [21]:
scalar.dtype

torch.int64

In [22]:
new_scalar = torch.tensor(25, dtype=torch.int32)

In [23]:
new_scalar.dtype

torch.int32

In [24]:
new_scalar + 10

tensor(35, dtype=torch.int32)

In [25]:
tensor_float = torch.tensor(3.14)

In [26]:
tensor_float

tensor(3.1400)

### Vectors

In [27]:
vector = torch.tensor([1, 9])

In [28]:
vector

tensor([1, 9])

In [29]:
vector.shape

torch.Size([2])

In [30]:
vector.dtype

torch.int64

In [31]:
vector.ndim

1

In [32]:
vector = torch.tensor([1, 2, 3])

In [33]:
vector.dim

<function Tensor.dim()>

In [34]:
vector.ndim

1

In [35]:
vector.shape

torch.Size([3])

### Count # of [ -> dimension
### Count elements -> shape

In [37]:
matrix = torch.tensor([[1, 9],[0, 7]])
print(f"Dimension: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

Dimension: 2
Shape: torch.Size([2, 2])


In [47]:
tensor_example = torch.tensor([
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], 
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ], 
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]
    ]
], device=None, requires_grad = False)
tensor_example

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [44]:
print(f"Dimension: {tensor_example.ndim}")
print(f"Shape: {tensor_example.shape}")

Dimension: 3
Shape: torch.Size([3, 3, 3])
