In [2]:
import torch
import numpy as np

In [5]:
random_array = np.random.randn(3, 5)

In [6]:
random_array

array([[ 1.81896126,  2.21624211, -0.18959625,  0.30231772, -0.1360718 ],
       [-1.3364406 ,  1.24722251,  0.17995201,  0.40022654, -1.00145836],
       [-0.77303927, -1.05538632,  1.21883357, -0.75010053, -0.7673776 ]])

In [11]:
print(f"Type: {type(random_array)}")
print(f"Shape: {random_array.shape}")
print(f"Dimension: {random_array.ndim}")

Type: <class 'numpy.ndarray'>
Shape: (3, 5)
Dimension: 2


In [15]:
random_matrix = torch.rand(size = (3, 6))
print(f"Type: {type(random_matrix)}")
print(f"Shape: {random_matrix.shape}")
print(f"Dimension: {random_matrix.ndim}")

Type: <class 'torch.Tensor'>
Shape: torch.Size([3, 6])
Dimension: 2


In [16]:
random_matrix

tensor([[0.6650, 0.7668, 0.1833, 0.2811, 0.7300, 0.6228],
        [0.1440, 0.3823, 0.5436, 0.5472, 0.2594, 0.9729],
        [0.3001, 0.2048, 0.9868, 0.6364, 0.5797, 0.4977]])

In [17]:
random_image_tensor = torch.rand(size=(224,224,3))

In [18]:
random_image_tensor

tensor([[[0.5732, 0.1298, 0.7826],
         [0.6618, 0.8852, 0.6439],
         [0.2902, 0.9468, 0.3014],
         ...,
         [0.0818, 0.2056, 0.8668],
         [0.3027, 0.7829, 0.1511],
         [0.7538, 0.4616, 0.6167]],

        [[0.6408, 0.2851, 0.3667],
         [0.1168, 0.7249, 0.5638],
         [0.1609, 0.2950, 0.9808],
         ...,
         [0.8728, 0.0051, 0.2715],
         [0.2327, 0.6138, 0.4873],
         [0.8598, 0.9990, 0.3172]],

        [[0.1243, 0.6015, 0.8664],
         [0.6747, 0.5311, 0.5650],
         [0.4490, 0.5256, 0.2228],
         ...,
         [0.5363, 0.8117, 0.3087],
         [0.9654, 0.5706, 0.0714],
         [0.7333, 0.1551, 0.0346]],

        ...,

        [[0.8613, 0.3843, 0.6899],
         [0.0172, 0.5042, 0.9606],
         [0.8518, 0.4873, 0.0865],
         ...,
         [0.4995, 0.7114, 0.2917],
         [0.5801, 0.3484, 0.7477],
         [0.3443, 0.7845, 0.3718]],

        [[0.5186, 0.6928, 0.5262],
         [0.7762, 0.6384, 0.8735],
         [0.

In [20]:
zeros = torch.zeros(size = (3, 2))
zeros

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [22]:
ones = torch.ones(size = (3, 2))
ones

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [28]:
vector_with_arange = torch.arange(start=0, end=100, step=1)
vector_with_arange

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
        72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [31]:
similar_ones = torch.ones_like(input=random_image_tensor)
similar_ones

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        ...,

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         ...,
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [35]:
x_tensor = torch.tensor([1, 2, 3])
x_tensor

tensor([1, 2, 3])

In [36]:
print("Arithmetical Operations")
print(f"x_tensor + 5 = {x_tensor + 5}")
print(f"x_tensor - 5 = {x_tensor - 5}")
print(f"x_tensor * 5 = {x_tensor * 5}")
print(f"x_tensor / 5 = {x_tensor / 5}")

Arithmetical Operations
x_tensor + 5 = tensor([6, 7, 8])
x_tensor - 5 = tensor([-4, -3, -2])
x_tensor * 5 = tensor([ 5, 10, 15])
x_tensor / 5 = tensor([0.2000, 0.4000, 0.6000])


In [38]:
print("Arithmetical Operations with Functions")
print(f"x_tensor + 5 = {x_tensor.add(5)}")
print(f"x_tensor - 5 = {x_tensor.subtract(5)}")
print(f"x_tensor * 5 = {x_tensor.multiply(5)}")
print(f"x_tensor / 5 = {x_tensor.divide(5)}")

Arithmetical Operations with Functions
x_tensor + 5 = tensor([6, 7, 8])
x_tensor - 5 = tensor([-4, -3, -2])
x_tensor * 5 = tensor([ 5, 10, 15])
x_tensor / 5 = tensor([0.2000, 0.4000, 0.6000])


In [40]:
print("Arithmetical Operations between tensors")
print(f"x_tensor + x_tensor = {x_tensor.add(x_tensor)}")
print(f"x_tensor - x_tensor = {x_tensor.subtract(x_tensor)}")
print(f"x_tensor * x_tensor = {x_tensor.multiply(x_tensor)}")
print(f"x_tensor / x_tensor = {x_tensor.divide(x_tensor)}")

Arithmetical Operations between tensors
x_tensor + x_tensor = tensor([2, 4, 6])
x_tensor - x_tensor = tensor([0, 0, 0])
x_tensor * x_tensor = tensor([1, 4, 9])
x_tensor / x_tensor = tensor([1., 1., 1.])
