In [2]:
import torch
import numpy as np

In [4]:
tensor = torch.tensor([1, 2, 3])

In [5]:
tensor * tensor

tensor([1, 4, 9])

In [6]:
matrix = torch.tensor(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        
    ]
)

In [7]:
matrix * matrix

tensor([[ 1,  4,  9],
        [16, 25, 36],
        [49, 64, 81]])

In [8]:
matrix @ matrix

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [9]:
torch.matmul(matrix, matrix)

tensor([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

In [12]:
matrix.shape

torch.Size([3, 3])

In [17]:
tempTensor1 = torch.randn(size=(3, 2))
tempTensor1


tensor([[ 1.1667,  0.5790],
        [-0.6767, -0.6468],
        [-0.0809, -1.1110]])

In [16]:
tempTensor2 = torch.randn(size=(3, 2))
tempTensor2

tensor([[ 1.3425, -0.2125],
        [ 0.6645, -2.9376],
        [-0.8816, -1.3572]])

In [23]:
# tempTensor1 @ tempTensor2 will cause error
tempTensor1 @ tempTensor2.T

tensor([[ 1.4433, -0.9257, -1.8145],
        [-0.7711,  1.4502,  1.4744],
        [ 0.1275,  3.2100,  1.5792]])

In [25]:
A = torch.randn(size = (1, 3))
A

tensor([[-0.2343,  0.6808,  0.4027]])

In [30]:
B = torch.randn(size = (3, 1))
B

tensor([[0.5499],
        [0.1264],
        [0.2392]])

In [28]:
A @ B

tensor([[0.0936]])